version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payflow-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payflow_db
      POSTGRES_USER: payflow_user
      POSTGRES_PASSWORD: payflow_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payflow-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payflow-pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - payflow-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payflow-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payflow_db
      SPRING_DATASOURCE_USERNAME: payflow_user
      SPRING_DATASOURCE_PASSWORD: payflow_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: 'false'
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRATION: 86400000
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - payflow-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  payflow-network:
    driver: bridge